#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OGSAndroid.Resource", IsApplication=true)]

namespace OGSAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FlatUI.Resource.Attribute.backgroundColor = global::OGSAndroid.Resource.Attribute.backgroundColor;
			global::FlatUI.Resource.Attribute.cornerRadius = global::OGSAndroid.Resource.Attribute.cornerRadius;
			global::FlatUI.Resource.Attribute.customBackgroundColor = global::OGSAndroid.Resource.Attribute.customBackgroundColor;
			global::FlatUI.Resource.Attribute.fieldStyle = global::OGSAndroid.Resource.Attribute.fieldStyle;
			global::FlatUI.Resource.Attribute.fontFamily = global::OGSAndroid.Resource.Attribute.fontFamily;
			global::FlatUI.Resource.Attribute.fontWeight = global::OGSAndroid.Resource.Attribute.fontWeight;
			global::FlatUI.Resource.Attribute.isFullFlat = global::OGSAndroid.Resource.Attribute.isFullFlat;
			global::FlatUI.Resource.Attribute.size = global::OGSAndroid.Resource.Attribute.size;
			global::FlatUI.Resource.Attribute.textAppearance = global::OGSAndroid.Resource.Attribute.textAppearance;
			global::FlatUI.Resource.Attribute.textColor = global::OGSAndroid.Resource.Attribute.textColor;
			global::FlatUI.Resource.Attribute.textPadding = global::OGSAndroid.Resource.Attribute.textPadding;
			global::FlatUI.Resource.Attribute.theme = global::OGSAndroid.Resource.Attribute.theme;
			global::FlatUI.Resource.Id.Comfortaa = global::OGSAndroid.Resource.Id.Comfortaa;
			global::FlatUI.Resource.Id.DroidSans = global::OGSAndroid.Resource.Id.DroidSans;
			global::FlatUI.Resource.Id.OpenSans = global::OGSAndroid.Resource.Id.OpenSans;
			global::FlatUI.Resource.Id.Roboto = global::OGSAndroid.Resource.Id.Roboto;
			global::FlatUI.Resource.Id.bold = global::OGSAndroid.Resource.Id.bold;
			global::FlatUI.Resource.Id.box = global::OGSAndroid.Resource.Id.box;
			global::FlatUI.Resource.Id.dark = global::OGSAndroid.Resource.Id.dark;
			global::FlatUI.Resource.Id.darker = global::OGSAndroid.Resource.Id.darker;
			global::FlatUI.Resource.Id.extrabold = global::OGSAndroid.Resource.Id.extrabold;
			global::FlatUI.Resource.Id.extralight = global::OGSAndroid.Resource.Id.extralight;
			global::FlatUI.Resource.Id.flat = global::OGSAndroid.Resource.Id.flat;
			global::FlatUI.Resource.Id.light = global::OGSAndroid.Resource.Id.light;
			global::FlatUI.Resource.Id.main = global::OGSAndroid.Resource.Id.main;
			global::FlatUI.Resource.Id.none = global::OGSAndroid.Resource.Id.none;
			global::FlatUI.Resource.Id.regular = global::OGSAndroid.Resource.Id.regular;
			global::FlatUI.Resource.Id.transparent = global::OGSAndroid.Resource.Id.transparent;
			global::FlatUI.Resource.String.library_name = global::OGSAndroid.Resource.String.library_name;
			global::FlatUI.Resource.Styleable.FlatUI = global::OGSAndroid.Resource.Styleable.FlatUI;
			global::FlatUI.Resource.Styleable.FlatUI_backgroundColor = global::OGSAndroid.Resource.Styleable.FlatUI_backgroundColor;
			global::FlatUI.Resource.Styleable.FlatUI_cornerRadius = global::OGSAndroid.Resource.Styleable.FlatUI_cornerRadius;
			global::FlatUI.Resource.Styleable.FlatUI_customBackgroundColor = global::OGSAndroid.Resource.Styleable.FlatUI_customBackgroundColor;
			global::FlatUI.Resource.Styleable.FlatUI_fieldStyle = global::OGSAndroid.Resource.Styleable.FlatUI_fieldStyle;
			global::FlatUI.Resource.Styleable.FlatUI_fontFamily = global::OGSAndroid.Resource.Styleable.FlatUI_fontFamily;
			global::FlatUI.Resource.Styleable.FlatUI_fontWeight = global::OGSAndroid.Resource.Styleable.FlatUI_fontWeight;
			global::FlatUI.Resource.Styleable.FlatUI_isFullFlat = global::OGSAndroid.Resource.Styleable.FlatUI_isFullFlat;
			global::FlatUI.Resource.Styleable.FlatUI_size = global::OGSAndroid.Resource.Styleable.FlatUI_size;
			global::FlatUI.Resource.Styleable.FlatUI_textAppearance = global::OGSAndroid.Resource.Styleable.FlatUI_textAppearance;
			global::FlatUI.Resource.Styleable.FlatUI_textColor = global::OGSAndroid.Resource.Styleable.FlatUI_textColor;
			global::FlatUI.Resource.Styleable.FlatUI_textPadding = global::OGSAndroid.Resource.Styleable.FlatUI_textPadding;
			global::FlatUI.Resource.Styleable.FlatUI_theme = global::OGSAndroid.Resource.Styleable.FlatUI_theme;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000a
			public const int backgroundColor = 2130771978;
			
			// aapt resource value: 0x7f010004
			public const int cornerRadius = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int customBackgroundColor = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int fieldStyle = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int fontFamily = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int fontWeight = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int isFullFlat = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int size = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int textAppearance = 2130771969;
			
			// aapt resource value: 0x7f010009
			public const int textColor = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int textPadding = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int theme = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int woodtex = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Comfortaa = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int DroidSans = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int OpenSans = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Roboto = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int SGFView = 2131099665;
			
			// aapt resource value: 0x7f06001e
			public const int blackImage = 2131099678;
			
			// aapt resource value: 0x7f060007
			public const int bold = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int box = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int button2 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int button3 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int button4 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int button5 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int button6 = 2131099672;
			
			// aapt resource value: 0x7f060000
			public const int dark = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int darker = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int extrabold = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int extralight = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int flat = 2131099660;
			
			// aapt resource value: 0x7f060025
			public const int gameList = 2131099685;
			
			// aapt resource value: 0x7f060001
			public const int light = 2131099649;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout1 = 2131099667;
			
			// aapt resource value: 0x7f060020
			public const int linearLayout2 = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout3 = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout4 = 2131099673;
			
			// aapt resource value: 0x7f06000f
			public const int main = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int moveText = 2131099675;
			
			// aapt resource value: 0x7f060012
			public const int myButton = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int none = 2131099650;
			
			// aapt resource value: 0x7f060023
			public const int pNameText = 2131099683;
			
			// aapt resource value: 0x7f06000a
			public const int regular = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int relativeLayout1 = 2131099664;
			
			// aapt resource value: 0x7f060024
			public const int searchButton = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int textBlack = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int textWhite = 2131099682;
			
			// aapt resource value: 0x7f06001c
			public const int toolbarButton = 2131099676;
			
			// aapt resource value: 0x7f06001a
			public const int topToolbarLayout = 2131099674;
			
			// aapt resource value: 0x7f06000d
			public const int transparent = 2131099661;
			
			// aapt resource value: 0x7f06001f
			public const int whiteImage = 2131099679;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PlayerGameList = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlatUI = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 10
			public const int FlatUI_backgroundColor = 10;
			
			// aapt resource value: 4
			public const int FlatUI_cornerRadius = 4;
			
			// aapt resource value: 11
			public const int FlatUI_customBackgroundColor = 11;
			
			// aapt resource value: 8
			public const int FlatUI_fieldStyle = 8;
			
			// aapt resource value: 2
			public const int FlatUI_fontFamily = 2;
			
			// aapt resource value: 3
			public const int FlatUI_fontWeight = 3;
			
			// aapt resource value: 7
			public const int FlatUI_isFullFlat = 7;
			
			// aapt resource value: 6
			public const int FlatUI_size = 6;
			
			// aapt resource value: 1
			public const int FlatUI_textAppearance = 1;
			
			// aapt resource value: 9
			public const int FlatUI_textColor = 9;
			
			// aapt resource value: 5
			public const int FlatUI_textPadding = 5;
			
			// aapt resource value: 0
			public const int FlatUI_theme = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
