#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OGSAndroid.Resource", IsApplication=true)]

namespace OGSAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FlatUI.Resource.Attribute.backgroundColor = global::OGSAndroid.Resource.Attribute.backgroundColor;
			global::FlatUI.Resource.Attribute.cornerRadius = global::OGSAndroid.Resource.Attribute.cornerRadius;
			global::FlatUI.Resource.Attribute.customBackgroundColor = global::OGSAndroid.Resource.Attribute.customBackgroundColor;
			global::FlatUI.Resource.Attribute.fieldStyle = global::OGSAndroid.Resource.Attribute.fieldStyle;
			global::FlatUI.Resource.Attribute.fontFamily = global::OGSAndroid.Resource.Attribute.fontFamily;
			global::FlatUI.Resource.Attribute.fontWeight = global::OGSAndroid.Resource.Attribute.fontWeight;
			global::FlatUI.Resource.Attribute.isFullFlat = global::OGSAndroid.Resource.Attribute.isFullFlat;
			global::FlatUI.Resource.Attribute.size = global::OGSAndroid.Resource.Attribute.size;
			global::FlatUI.Resource.Attribute.textAppearance = global::OGSAndroid.Resource.Attribute.textAppearance;
			global::FlatUI.Resource.Attribute.textColor = global::OGSAndroid.Resource.Attribute.textColor;
			global::FlatUI.Resource.Attribute.textPadding = global::OGSAndroid.Resource.Attribute.textPadding;
			global::FlatUI.Resource.Attribute.theme = global::OGSAndroid.Resource.Attribute.theme;
			global::FlatUI.Resource.Id.Comfortaa = global::OGSAndroid.Resource.Id.Comfortaa;
			global::FlatUI.Resource.Id.DroidSans = global::OGSAndroid.Resource.Id.DroidSans;
			global::FlatUI.Resource.Id.OpenSans = global::OGSAndroid.Resource.Id.OpenSans;
			global::FlatUI.Resource.Id.Roboto = global::OGSAndroid.Resource.Id.Roboto;
			global::FlatUI.Resource.Id.bold = global::OGSAndroid.Resource.Id.bold;
			global::FlatUI.Resource.Id.box = global::OGSAndroid.Resource.Id.box;
			global::FlatUI.Resource.Id.dark = global::OGSAndroid.Resource.Id.dark;
			global::FlatUI.Resource.Id.darker = global::OGSAndroid.Resource.Id.darker;
			global::FlatUI.Resource.Id.extrabold = global::OGSAndroid.Resource.Id.extrabold;
			global::FlatUI.Resource.Id.extralight = global::OGSAndroid.Resource.Id.extralight;
			global::FlatUI.Resource.Id.flat = global::OGSAndroid.Resource.Id.flat;
			global::FlatUI.Resource.Id.light = global::OGSAndroid.Resource.Id.light;
			global::FlatUI.Resource.Id.main = global::OGSAndroid.Resource.Id.main;
			global::FlatUI.Resource.Id.none = global::OGSAndroid.Resource.Id.none;
			global::FlatUI.Resource.Id.regular = global::OGSAndroid.Resource.Id.regular;
			global::FlatUI.Resource.Id.transparent = global::OGSAndroid.Resource.Id.transparent;
			global::FlatUI.Resource.String.library_name = global::OGSAndroid.Resource.String.library_name;
			global::FlatUI.Resource.Styleable.FlatUI = global::OGSAndroid.Resource.Styleable.FlatUI;
			global::FlatUI.Resource.Styleable.FlatUI_backgroundColor = global::OGSAndroid.Resource.Styleable.FlatUI_backgroundColor;
			global::FlatUI.Resource.Styleable.FlatUI_cornerRadius = global::OGSAndroid.Resource.Styleable.FlatUI_cornerRadius;
			global::FlatUI.Resource.Styleable.FlatUI_customBackgroundColor = global::OGSAndroid.Resource.Styleable.FlatUI_customBackgroundColor;
			global::FlatUI.Resource.Styleable.FlatUI_fieldStyle = global::OGSAndroid.Resource.Styleable.FlatUI_fieldStyle;
			global::FlatUI.Resource.Styleable.FlatUI_fontFamily = global::OGSAndroid.Resource.Styleable.FlatUI_fontFamily;
			global::FlatUI.Resource.Styleable.FlatUI_fontWeight = global::OGSAndroid.Resource.Styleable.FlatUI_fontWeight;
			global::FlatUI.Resource.Styleable.FlatUI_isFullFlat = global::OGSAndroid.Resource.Styleable.FlatUI_isFullFlat;
			global::FlatUI.Resource.Styleable.FlatUI_size = global::OGSAndroid.Resource.Styleable.FlatUI_size;
			global::FlatUI.Resource.Styleable.FlatUI_textAppearance = global::OGSAndroid.Resource.Styleable.FlatUI_textAppearance;
			global::FlatUI.Resource.Styleable.FlatUI_textColor = global::OGSAndroid.Resource.Styleable.FlatUI_textColor;
			global::FlatUI.Resource.Styleable.FlatUI_textPadding = global::OGSAndroid.Resource.Styleable.FlatUI_textPadding;
			global::FlatUI.Resource.Styleable.FlatUI_theme = global::OGSAndroid.Resource.Styleable.FlatUI_theme;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000a
			public const int backgroundColor = 2130771978;
			
			// aapt resource value: 0x7f010004
			public const int cornerRadius = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int customBackgroundColor = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int fieldStyle = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int fontFamily = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int fontWeight = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int isFullFlat = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int size = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int textAppearance = 2130771969;
			
			// aapt resource value: 0x7f010009
			public const int textColor = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int textPadding = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int theme = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlackBorder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkbox = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int defaultuser = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int GradientDither = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int WhiteBorder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int woodtex = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int Comfortaa = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int DroidSans = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int OpenSans = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Roboto = 2131165190;
			
			// aapt resource value: 0x7f07001c
			public const int SGFView = 2131165212;
			
			// aapt resource value: 0x7f070028
			public const int blackImage = 2131165224;
			
			// aapt resource value: 0x7f070007
			public const int bold = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int box = 2131165195;
			
			// aapt resource value: 0x7f07001e
			public const int button2 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int button3 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int button4 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int button5 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int button6 = 2131165218;
			
			// aapt resource value: 0x7f070031
			public const int chatText = 2131165233;
			
			// aapt resource value: 0x7f070011
			public const int clientIdText = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int dark = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int darker = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int editText2 = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int extrabold = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int extralight = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int flat = 2131165196;
			
			// aapt resource value: 0x7f070035
			public const int gameList = 2131165237;
			
			// aapt resource value: 0x7f070001
			public const int light = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout1 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int linearLayout2 = 2131165209;
			
			// aapt resource value: 0x7f070027
			public const int linearLayout3 = 2131165223;
			
			// aapt resource value: 0x7f070023
			public const int linearLayout4 = 2131165219;
			
			// aapt resource value: 0x7f07002f
			public const int linearLayout5 = 2131165231;
			
			// aapt resource value: 0x7f070034
			public const int loadingPanel = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int loadingPanelInfinite = 2131165238;
			
			// aapt resource value: 0x7f070017
			public const int loginButton = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int loginGuestButton = 2131165208;
			
			// aapt resource value: 0x7f070010
			public const int loginTextView1 = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int loginTextView2 = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int main = 2131165199;
			
			// aapt resource value: 0x7f070025
			public const int moveText = 2131165221;
			
			// aapt resource value: 0x7f07001d
			public const int myButton = 2131165213;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			
			// aapt resource value: 0x7f070032
			public const int pNameText = 2131165234;
			
			// aapt resource value: 0x7f07000a
			public const int regular = 2131165194;
			
			// aapt resource value: 0x7f070013
			public const int relativeLayout1 = 2131165203;
			
			// aapt resource value: 0x7f07002e
			public const int rightDrawer = 2131165230;
			
			// aapt resource value: 0x7f07002c
			public const int rightDrawerContent = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int rightDrawerHandle = 2131165229;
			
			// aapt resource value: 0x7f070030
			public const int rightDrawerScroll = 2131165232;
			
			// aapt resource value: 0x7f070014
			public const int saveDetailsCheckBox = 2131165204;
			
			// aapt resource value: 0x7f070033
			public const int searchButton = 2131165235;
			
			// aapt resource value: 0x7f07002a
			public const int textBlack = 2131165226;
			
			// aapt resource value: 0x7f07001a
			public const int textView1 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int textView2 = 2131165211;
			
			// aapt resource value: 0x7f07002b
			public const int textWhite = 2131165227;
			
			// aapt resource value: 0x7f070026
			public const int toolbarButton = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int topToolbarLayout = 2131165220;
			
			// aapt resource value: 0x7f07000d
			public const int transparent = 2131165197;
			
			// aapt resource value: 0x7f070029
			public const int whiteImage = 2131165225;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PlayerGameList = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int data = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int HelpLoginUrl = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int RegisterLoginUrl = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlatUI = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 10
			public const int FlatUI_backgroundColor = 10;
			
			// aapt resource value: 4
			public const int FlatUI_cornerRadius = 4;
			
			// aapt resource value: 11
			public const int FlatUI_customBackgroundColor = 11;
			
			// aapt resource value: 8
			public const int FlatUI_fieldStyle = 8;
			
			// aapt resource value: 2
			public const int FlatUI_fontFamily = 2;
			
			// aapt resource value: 3
			public const int FlatUI_fontWeight = 3;
			
			// aapt resource value: 7
			public const int FlatUI_isFullFlat = 7;
			
			// aapt resource value: 6
			public const int FlatUI_size = 6;
			
			// aapt resource value: 1
			public const int FlatUI_textAppearance = 1;
			
			// aapt resource value: 9
			public const int FlatUI_textColor = 9;
			
			// aapt resource value: 5
			public const int FlatUI_textPadding = 5;
			
			// aapt resource value: 0
			public const int FlatUI_theme = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
